name: Google Cloud Storage Synchronization

# Run after push into main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Synchronize files
    runs-on: ubuntu-24.04

    env:
      GIT_SUBFOLDER: rep

    steps:
      - name: 1. Get data from repo
        uses: actions/checkout@v4
        with:
          path: ${{env.GIT_SUBFOLDER}}

      - name: 2. Authorize with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.google_cloud_storage }}

      - name: 3. Prepare Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 4. Synchronize files
        run: |
          SOURCE_FOLDER="${{env.GIT_SUBFOLDER}}" # Source folder that will be synchronized.
          TARGET_BUCKET="folder_cz" # Target bucket in GCS.
          TARGET_FOLDER="subfolder" # Target folder in GCS bucket where data will be synchronized. Data that are missing in Git will be automatically dropped.
          IGNORE=".*\.pbix$|\.gitignore$|\.git/.*$|\.github/.*$" # Ignore files and folders.
          gsutil -m rsync -r -c -d -x "$IGNORE" $SOURCE_FOLDER gs://$TARGET_BUCKET/$TARGET_FOLDER