name: Google Cloud Storage Synchronization

# Run after new push into main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Synchronize files
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get data from repo
        uses: actions/checkout@v4

      - name: 2. Synchronize all files
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'petr-test@dev-petr.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.google_cloud_storage }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'upload-folder'
        run: |
          gsutil -m rsync -r -c -d -x ".*\.pbix$|\.gitignore$|\.git/.*$|\.github/.*$" beta gs://folder_cz/subfolder