name: Google Cloud Storage Synchronization

# Run after new push into main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Synchronize files
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get data from repo
        uses: actions/checkout@v4

      - name: 2. Authorize with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.google_cloud_storage }}

      - name: 3. Prepare Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 4. Synchronize files
        run: |
          gsutil -m rsync -r -c -d -x ".*\.pbix$|\.gitignore$|\.git/.*$|\.github/.*$" beta gs://folder_cz/subfolder