name: Google Cloud Storage Synchronization

# Run after new push into main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Synchronize files
    runs-on: ubuntu-latest
    steps:
      - name: 1. Get data from repo
        uses: actions/checkout@v4

      - name: 2. Synchronize all files
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: 'petr-test@dev-petr.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.google_cloud_storage }}

      - name: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'beta'
          destination: 'folder_cz/subfolder'